public enum EPopupType
{
    UI_MapSelectPopup,
    UI_RoomSearchPopup,
    UI_RoomMakerPopup,
    UI_SystemPopup,
    UI_GameStartPopup,
    UI_FriendsListPopup,
    UI_PasswordPopup,
    UI_PasswordWrongPopup,
    UI_EmotionPopup,
    UI_MessagePopup,
    UI_SettingPopup,
    UI_MenuPopup,
    UI_InformationPopup,
    UI_WithdrawPopup,
    UI_ItemStorage,
    UI_IngameChatPopup,
    UI_TempStorage,
    UI_CartridgeShopPopup,
    Count
}